apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: appdb-east-store
  namespace: db-east
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://cnpg-backups/
    endpointURL: http://minio.storage.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: minio-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio-creds
        key: ACCESS_SECRET_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
      maxParallel: 8
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: appdb-east-source-store
  namespace: db-west
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://cnpg-backups/
    endpointURL: http://minio.storage.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: minio-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio-creds
        key: ACCESS_SECRET_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
      maxParallel: 8
