apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crunchy-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:americancode/cnpg-learning.git
    targetRevision: HEAD
    path: dump
  destination:
    server: https://kubernetes.default.svc
    namespace: crunchy-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
