apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crunchy-demo-app-password
  namespace: crunchy-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: crunchy-demo-app-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: crunchy-demo/app-password
        property: password
