apiVersion: v1
kind: Secret
metadata:
  name: crunchy-source-migrator
  namespace: migration-db
type: Opaque
stringData:
  password: "E@QJT-vx{YYDC6W{e==Xd9;K"
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-target-superuser
  namespace: migration-db
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: "E@QJT-vx{YYDC6W{e==Xd9;K"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-target
  namespace: migration-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  imagePullPolicy: IfNotPresent
  enableSuperuserAccess: true
  superuserSecret:
    name: cnpg-target-superuser
  bootstrap:
    pg_basebackup:
      source: crunchy-source
  storage:
    size: 5Gi
  backup:
    barmanObjectStore:
      destinationPath: s3://crunchy-cnpg-migration/cnpg-target
      endpointURL: http://minio.migration-db.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-creds
          key: ACCESS_SECRET_KEY
      data:
        compression: gzip
      wal:
        compression: gzip
        maxParallel: 8
    retentionPolicy: 7d
  externalClusters:
    - name: crunchy-source
      connectionParameters:
        host: crunchy-source-primary.migration-db.svc
        user: migrator
        dbname: app
        sslmode: require
      password:
        name: crunchy-source-migrator
        key: password
